language: objective-c
osx_image: xcode9.4

env:
  global:
    - PROJECT='UserDefaultsStore.xcodeproj'
    - SCHEME='UserDefaultsStore'
    - DESTINATION='platform=iOS Simulator,name=iPhone X'

before_install:
  - brew update
  - gem install xcpretty
  - brew outdated xctool || brew upgrade xctool

script:
  - set -o pipefail
  - xcodebuild clean build test -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty
  - bash <(curl -s https://codecov.io/bash) -cF ios -J 'UserDefaultsStore'
  - pod lib lint